### PR TITLE
build: set up CI with Azure Pipelines and Lighthouse

### PR DESCRIPTION
**Pull request by Lange**

### CODE REVIEW

**Comment by Lange** [comment]
I gotta figure out a better method for testing both themes

**Comment by Lange** [comment]
Well, I'm confused. The `/docs/classes/nodecg` route is being rendered with no style.

**Comment by Lange** [comment]
Actually all routes are being rendered with no style, sick

**Comment by Lange** [comment]
Ugh I see the problem, serving these things from subdirs doesn't work because the pages are hardcoded to serve from the root

**Comment by Lange** [comment]
Okay, Lighthouse is finally working. We can now work on getting the assertions to pass.

**Comment by Lange** [comment]
Ok, the last thing left is to fix the contrast of link colors I think. @EwanLyon got any suggestions for color schemes you think might look good here? I think that teal-on-white is just a nonstarter in terms of contrast ratio, not sure.

**Comment by EwanLyon** [comment]
I've been trying to stick with NodeCG colours for the design so we could try out the navy ones and see if they stand out and are still readable.

**Comment by Lange** [comment]
Kk -- if that doesn't work out, then we could dress up the links in other ways, maybe make them bolder (which reduces how different the colors need to be for them to have sufficient contrast), or use the brand colors as part of an underline or border, idk. Could get creative.

**Comment by Lange** [comment]
I went ahead and:
- squashed this branch
- rebased on master
- cherrypicked the existing work from `wcag-aaa` into this branch
- deleted the `wcag-aaa` branch

we can keep working on WCAG AAA on this branch until it passes CI

**Comment by Lange** [comment]
I also opened this issue regarding the readability of the HTML reports: https://github.com/GoogleChrome/lighthouse-ci/issues/232

**Comment by Lange** [comment]
Great! Thanks so much for the work on this PR @EwanLyon

**Pull request merged**
